# Application Name
spring.application.name=PegStock

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?postgres.ubfboelaroaqcmteqqyn&password=BD-PegAzuls#AERO30
spring.datasource.username=postgres.ubfboelaroaqcmteqqyn
spring.datasource.password=BD-PegAzuls#AERO30
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.error.include-stacktrace=never

# Disable Web Application (since this is a JavaFX application)
spring.main.web-application-type=none