-- Email : pegazuls@ufersa.edu.br Password: pegstock
-- INSERT INTO tb_user (name, email, password) VALUES
--     ('PegAzuls', 'pegazuls@ufersa.edu.br', '$2a$10$Qut7kGdi9ZP6N6zpmekT9OcfnPEhJJIC1On1oUOhU8ClHdEMKgWyu');

CREATE TABLE tb_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_user PRIMARY KEY (id)
);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_email UNIQUE (email);
