CREATE TABLE tb_material
(
    cod                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  VARCHAR(255),
    brand                 VARCHAR(255),
    description           VARCHAR(255),
    quantity              INTEGER                                 NOT NULL,
    consumer_quantity     INTEGER                                 NOT NULL,
    category              VARCHAR(255),
    box                   VARCHAR(255),
    expiration_date       date,
    created_date          date,
    register_date         date,
    last_add_date         date,
    last_consumption_date date,
    CONSTRAINT pk_tb_material PRIMARY KEY (cod)
);

CREATE TABLE tb_material_status
(
    material_id BIGINT NOT NULL,
    status      VARCHAR(255)
);

ALTER TABLE tb_material_status
    ADD CONSTRAINT fk_tb_material_status_on_material FOREIGN KEY (material_id) REFERENCES tb_material (cod);