CREATE TABLE tb_shopping_list
(
    cod          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name VARCHAR(255)                            NOT NULL,
    quantity     INTEGER                                 NOT NULL,
    price        DOUBLE PRECISION                        NOT NULL,
    supplier     VARCHAR(255)                            NOT NULL,
    date         date,
    link         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    total_value  DOUBLE PRECISION,
    material_cod BIGINT,
    CONSTRAINT pk_tb_shopping_list PRIMARY KEY (cod)
);

ALTER TABLE tb_shopping_list
    ADD CONSTRAINT FK_TB_SHOPPING_LIST_ON_MATERIAL_COD FOREIGN KEY (material_cod) REFERENCES tb_material (cod);