CREATE TABLE tb_borrowing
(
    cod             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity        INTEGER                                 NOT NULL,
    borrower        VARCHAR(255)                            NOT NULL,
    expiration_date date                                    NOT NULL,
    created_date    date                                    NOT NULL,
    returned        BOOLEAN                                 NOT NULL,
    responsible     VARCHAR(255)                            NOT NULL,
    material_cod    BIGINT,
    CONSTRAINT pk_tb_borrowing PRIMARY KEY (cod)
);

ALTER TABLE tb_borrowing
    ADD CONSTRAINT FK_TB_BORROWING_ON_MATERIAL_COD FOREIGN KEY (material_cod) REFERENCES tb_material (cod);