CREATE TABLE tb_brand
(
    cod         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    sector      VARCHAR(255)                            NOT NULL,
    sponsorship BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tb_brand PRIMARY KEY (cod)
);

ALTER TABLE tb_brand
    ADD CONSTRAINT uc_tb_brand_name UNIQUE (name);