CREATE TABLE executed_commands
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    command_name  VARCHAR(255),
    quantity      INTEGER                                 NOT NULL,
    material_name VARCHAR(255),
    executed_at   date,
    CONSTRAINT pk_executed_commands PRIMARY KEY (id)
);