CREATE TABLE tb_stock_movement
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    material_cod  BIGINT                                  NOT NULL,
    quantity      INTEGER                                 NOT NULL,
    type          VARCHAR(255)                            NOT NULL,
    movement_date date                                    NOT NULL,
    responsible   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_stock_movement PRIMARY KEY (id)
);

ALTER TABLE tb_stock_movement
    ADD CONSTRAINT FK_TB_STOCK_MOVEMENT_ON_MATERIAL_COD FOREIGN KEY (material_cod) REFERENCES tb_material (cod);